spring.application.name=backend

# Disable Docker Compose integration for now
spring.docker.compose.enabled=false

# =========================
# PostgreSQL Configuration
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/devhub
spring.datasource.username=postgres
spring.datasource.password=your@24#
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# =========================
# Server
# =========================
server.port=8080